### ISSUE TITLE
Various errors on keras/tensoflow and R/miniconda

### ISSUE THREAD

**Issue by drag05** [rstudio/tensorflow#417]
I am re-running a `keras` deep learning example on the REUTERS data that had worked before. 

Meanwhile I have updated to

`R v. 4.0.0` 
and on the `R` side I have 
 `keras v. 2.2.5.0`, 
`tensorflow v. 2.0.0` and 
` reticulate v. 1.15`

On `conda` side I have 
`python v. 3.7.7`,
`cudatoolkit v. 10.1.243`,
`cudnn v. 7.6.5`,
`tensorflow v. 2.1.0`
`tensorflow-gpu v. 2.1.0`

The errors - as they appear in RStudio are:

1. this error appears on the first attempt only
```
>  reuters <- dataset_reuters(num_words = 10000)

2020-04-29 14:59:02.124966: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'kerastools' has no attribute 'progbar'
```
2. this error is persistent
```
>  y_train <- to_categorical(train_labels)

Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'tensorflow.python.keras.utils' has no attribute 'to_categorical'
```

**Comment by dfalbel** [comment]
HI, both issues should e fixed in the dev version of keras (available from github). We are planning a CRAN release as soon as TensorFLow 2.2 is released.

**Comment by drag05** [comment]
@dfalbel 
Thank you for the prompt reply! Will R package `Tensorflow` be updated also?

**Comment by dfalbel** [comment]
yes! we are just waiting for the final 2.2 release to be sure we don't need to re-submit to CRAN if anything breaks.

**Comment by KKamojjala** [comment]
Is this issue resolved ? I updated tensorflow to 2.2 and I still see both the errors mentioned in the first post of this thread. 

y_train <- to_categorical(label_prep(train, list_img_train))
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'tensorflow.python.keras.utils' has no attribute 'to_categorical' 

Here is part of my sessioninfo from rstudio
reticulate_1.15  tensorflow_2.2.0 imager_0.42.1    magrittr_1.5     forcats_0.5.0    stringr_1.4.0    dplyr_0.8.5      purrr_0.3.4      readr_1.3.1     
[10] tidyr_1.0.3      tibble_3.0.1     ggplot2_3.3.0    tidyverse_1.3.0  keras_2.2.5.0  

Also please let me know if there is a workaround too or if you need anymore information

Thanks a lot
KC

**Comment by drag05** [comment]
@KKamojjala 
You need to install dev. version of keras

```
devtools::install_github('rstudio/keras')
```

**Comment by KKamojjala** [comment]
@drag05 

I already tried that as well. I removed the exisiting keras package and when I run that command.. I get the same version of keras as I mentioned earlier
keras_2.2.5.0. and also same error persists

I am not sure what to do at this point.

**Comment by drag05** [comment]
@KKamojjala 

I have the same keras version but installed from github. And this is what I have on the `Miniconda` site:


```
base environment:
python                    3.7.4                h5263a28_0 

tensorflow environment:
tensorboard               2.1.0                     py3_0
tensorflow                2.1.0           gpu_py37h7db9008_0
tensorflow-base           2.1.0           gpu_py37h55f5790_0
tensorflow-estimator      2.1.0              pyhd54b08b_0
tensorflow-gpu            2.1.0                h0d30ee6_0
```
 To have this, I have updated Miniconda then, updated environment `tensorflow`

**Comment by KKamojjala** [comment]
@drag05 

Thanks for your replies ! I think its working with the dev version. I don't know what I did previously, but I got pass that error.

Again, thanks a lot !

**Comment by drag05** [comment]
@KKamojjala 

Happy to be of help while learning for myself!

**Comment by cybersatori** [comment]
AttributeError: module 'tensorflow.python.keras.utils' has no attribute 'to_categorical'

got same bug but on Linux + Anaconda/Python + Jupyter solve it removing '' from tensorflow.python  import keras -> from tensorflow import keras ''
